# Generated by Django 4.2.7 on 2023-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('largo_del_tatuaje', models.IntegerField(choices=[[0, '10 centímetros'], [1, '15 centímetros'], [2, '20 centímetros'], [3, '25 centímetros'], [4, '30 centímetros']])),
                ('ancho_del_tatuaje', models.IntegerField(choices=[[0, '10 centímetros'], [1, '15 centímetros'], [2, '20 centímetros'], [3, '25 centímetros'], [4, '30 centímetros']])),
                ('parte_del_cuerpo_del_tatuaje', models.IntegerField(choices=[[0, 'brazo'], [1, 'pierna'], [2, 'pecho'], [3, 'espalda'], [4, 'abdomen'], [5, 'mano'], [6, 'otro']])),
                ('a_color_o_en_negro', models.IntegerField(choices=[[0, 'color'], [1, 'negro'], [2, 'indeciso']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
