# Generated by Django 4.2.7 on 2023-12-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_turnos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turnos',
            old_name='mensaje',
            new_name='descripcion',
        ),
    ]
